org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# Disable Kotlin incremental compilation to prevent "different roots" exception when Pub cache is on C: and project is on D:
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.incremental.jvm=false
